### ISSUE TITLE
Email priority - mailer

### ISSUE THREAD

**Issue by roberuto** [TheSoftwareHouse/rad-modules-tools#11]
Following the documentation for mailer service/client, the default priority should be `urgent`, however, I believe it is not the case. 

When using mailer client service with typescript, enum is required to set priority, I cannot use string value. I think it will be nice to enable easy import of EmailQueuePriority enum.

I also think it would be nice to stress out at the early point of the documentation that the template id refers to the folder name.

**Comment by sethii** [comment]
There is a option to use TS Enums defined inside this package - I've added an example of how to do that.
Also changed the documentation for priority has no longer default option.
